### PR TITLE
Made AvroScheme unpack/pack to a specifiable depth, supported arbitrary unions, made Avro conversion logic pluggable.

### PR DESCRIPTION
**Pull request by silasdavis**
New version of the this pull request targetting the 2.6 branch (see previous version at https://github.com/ScaleUnlimited/cascading.avro/pull/36). Adopting the Avro/Hadoop version of that branch, so no longer stating that this includes a version bump.

Some changes since since the first commit of the the old pull request are highlighted below in bold.

**Changes:**
- Unified the notions of AvroScheme and PackedAvroScheme with a depth paramter (how far should we unpack records into TupleEntries). This is mostly to support ShallowAvroScheme which is a TupleEntry representing an outer Avro record, but leaves any first children Avro record fields as Avro records. Adding AvroSpecificRecordSerialization to the JobConf `io.serializations` means we get intermediate serializability when doing this.
- Made the conversion logic between Avro and 'Cascading' types pluggable. There are various ways we may want to represent logical Avro records in Cascading, I've split and tidied up this logic so that you can provide your own classes implementing the interface AvroConverter<TRecordFrom,TRecordTo>, or you subclass one of the conversion classes (themselves sharing common traversal logic, pivoting on a Schema, in AvroConverterBase).
- Supported fairly arbitary union types. **Ttry candidate union element types, trying alternatives on case of exception**. It is conceivable that with a weird-enough union type (such as one containing a string array and a string map) that the conversion won't give you what you want, but I think it most cases it should be adequate and certainly improves on what was there.
- Increased the flexibility of Avro conversion logic with respect to `byte[]`, `List`, `TupleEntry`, `Map` etc by capturing the many-to-many nature of the type mappings in `CascadingToAvro`
- Standardised by representing Avro maps and arrays as Tuples, and records as TupleEntries in Cascading land. Provided helpers to convert to maps. This means intermediate serialisations (such as TempHfs and others) don't break (requiring extra stages in pipeline) when dealing with GroupBy and other aggregations (Cascading doesn't know how to serialise lone java Maps and Lists - but you can embed them in Avro records if you like).
- **Made CascadingToAvro use a ordered MultiMap to define mappings from Java classes to Avro Schema.Type's, order is used to determine preference of different destination types within unions**
- Made CascadingToAvro serialize into SpecificRecords~~ via `SpecificData.get().getClass(schema)`. Just downcast the the converted `IndexedRecord`.
- **Replaced AvroSpecificRecordSerialization with a more general AvroSpecificDataSerialization that servers all auto-generated Avro Java classes (that are also either GenericContainers and Enums). AvroSpecificRecordSerialization had some code quality, performance, and stability issues.** 
- Updated some test logic
- Added some tests

### CODE REVIEW

**Comment by silasdavis** [comment]
@kkrugler so this is rebased against version-2.6 and I've squashed my commits.

**Comment by silasdavis** [comment]
If it would be helpful to talk over this commit in realtime then you could create a gitter room for this repo: https://gitter.im

I'm around for a few hours today, and should have some time next week.

**Comment by kkrugler** [comment]
Hi Silas - I've merged, and updated the 2.6 branch.

You're right, it's a pretty beefy change...but so far it looks good. I'm going to ping Chris to do a review before we release, as he's got more recent experience with Avro.

Also, I added a CHANGES.txt file, which I find useful in other projects to provide an overview of what changed with each release. I've added notes for changes before this pull request, please update with your list.

Finally, should we switch to Hadoop 2.4 (currently at 2.2), now that 2.5 and 2.6 are both out?

**Comment by silasdavis** [comment]
I'd originally bumped to 2.4, but I reverted when making this pull request against version-2.6 since all I strictly needed was avro-1.7.7 (I think). I have been testing with hadoop-2.4 though so it would be preferable.

I'll add a condensed list of my changes and make another pull request with them.

**Comment by mjwillson** [comment]
Nice.

Note hadoop 2.4.0 is currently the highest version supported in EMR, which is why we (and perhaps others) are stuck on it:
http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-hadoop-version.html

**Comment by kkrugler** [comment]
Hi @silasdavis - it's been a while, so maybe you already did this...but were you able to create another pull request?

**Comment by soniclavier** [comment]
Hi, I see this as merged, but don't see the changes in "cascading.avro" % "avro-scheme" % "2.5.0". 
I am working with a Schema that has union types and I this change could help me.

**Pull request merged**
